ARDUINO_DIR            = /usr/share/arduino
TARGET                 = ecc
ARDUINO_LIBS           =
MCU                    = atmega328p
F_CPU                  = 16000000
ARDUINO_PORT           = /dev/ttyUSB0
AVRDUDE_ARD_BAUDRATE   = 115200
AVRDUDE_ARD_PROGRAMMER = arduino
 
include /usr/share/arduino/Arduino.mk

clean:
	rm -rf build-cli
